# Generated by Django 5.2 on 2025-05-12 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_userprofile_annualleave_alter_userprofile_wage_and_more'),
        ('staff', '0002_category_inventoryitem'),
    ]

    operations = [
    ]
