# Generated by Django 5.2 on 2025-05-12 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_inventoryitem_reorder_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Liter'), ('ml', 'Milliliter'), ('unit', 'Unit')], default='unit', max_length=10),
        ),
    ]
