# Generated by Django 5.2.1 on 2025-05-13 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_menuitem_alter_category_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='image',
        ),
    ]
